{% set name = "mysqlclient" %}
{% set version = "2.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 24ae22b59416d5fcce7e99c9d37548350b4565baac82f95e149cac6ce4163845

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vvv
  skip: true  # [py<38 or win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - python
    - pip
    - mysql-devel
    - setuptools >=61
    - wheel
  run:
    - python
    - mysql-devel

# Tests require connection: Can't connect to local MySQL server through socket '/tmp/mysql.sock'
{% set ignore_tests = "" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_MySQLdb_capabilities.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_MySQLdb_dbapi20.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_connection.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_cursor.py" %}
{% set ignore_tests = ignore_tests + " --ignore=tests/test_errors.py" %}
{% set ignore_tests = ignore_tests + " --deselect=tests/test_MySQLdb_nonstandard.py::CoreAPI::test_affected_rows" %}
{% set ignore_tests = ignore_tests + " --deselect=tests/test_MySQLdb_nonstandard.py::CoreAPI::test_charset_name" %}
{% set ignore_tests = ignore_tests + " --deselect=tests/test_MySQLdb_nonstandard.py::CoreAPI::test_client_flag" %}
{% set ignore_tests = ignore_tests + " --deselect=tests/test_MySQLdb_nonstandard.py::CoreAPI::test_context_manager" %}
{% set ignore_tests = ignore_tests + " --deselect=tests/test_MySQLdb_nonstandard.py::CoreAPI::test_fileno" %}
{% set ignore_tests = ignore_tests + " --deselect=tests/test_MySQLdb_nonstandard.py::CoreAPI::test_host_info" %}
{% set ignore_tests = ignore_tests + " --deselect=tests/test_MySQLdb_nonstandard.py::CoreAPI::test_proto_info" %}
{% set ignore_tests = ignore_tests + " --deselect=tests/test_MySQLdb_nonstandard.py::CoreAPI::test_server_info" %}
{% set ignore_tests = ignore_tests + " --deselect=tests/test_MySQLdb_nonstandard.py::CoreAPI::test_thread_id" %}
{% set ignore_tests = ignore_tests + " --deselect=tests/test_MySQLdb_nonstandard.py::TestCollation::test_charset_collation" %}

test:
  source_files:
    - tests
  imports:
    - MySQLdb
    - MySQLdb.constants
    - MySQLdb.cursors
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -vv {{ ignore_tests }} tests

about:
  home: https://github.com/PyMySQL/mysqlclient-python
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Python interface to MySQL
  description: |
    MySQLdb is an interface to the popular MySQL or MariaDB database servers that
    provides the Python database API.
  doc_url: https://mysqlclient.readthedocs.io
  dev_url: https://github.com/PyMySQL/mysqlclient

extra:
  recipe-maintainers:
    - halldc
